---

# MariaDB configuration tasks

- name: 'Manage configuration files'
  become: True
  ini_file:
    dest: "{{ item.0.path }}"
    section: "{{ item.1.section | default('mysqld') }}"
    option: "{{ item.1.option | default(omit) }}"
    value: "{{ item.1.value | default(omit) }}"
    state: "{{ item.1.state | default('present') }}"
  notify: 'Restart MariaDB'
  with_subelements:
    - "{{ mariadb_config_files }}"
    - 'items'


- name: 'Manage service'
  become: True
  service:
    name: "{{ mariadb_service_name }}"
    state: "{{ mariadb_service_state }}"
    enabled: "{{ mariadb_service_enabled }}"
