---

# Main tasks file for mariadb role

- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'mariadb::role'
    - 'mariadb::config'
    - 'mariadb::install'


- name: 'Manage install tasks'
  include: "install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'mariadb::role'
    - 'mariadb::install'


- name: 'Manage configuration tasks'
  include: 'config.yml'
  tags:
    - 'mariadb::role'
    - 'mariadb::config'


- name: 'Manage root credentials tasks'
  include: 'manage_root_account.yml'
  tags:
    - 'mariadb::role'
    - 'mariadb::config'


- name: 'Manage databases tasks'
  include: 'manage_databases.yml'
  tags:
    - 'mariadb::role'
    - 'mariadb::config'


- name: 'Manage credentials tasks'
  include: 'manage_accounts.yml'
  tags:
    - 'mariadb::role'
    - 'mariadb::config'
